# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3ca5b618ed1d249cf07728cf9d15278c4e245e6a77187b5460218cbc98ffaf4a2cc9bd5254eee95730a1264c53b491a25bde0637f3b00ae37abe2be38b161f6

test:
  secret_key_base: 743c19b2f84709b140d8887b5919758733510614f3989c0a2c89d7c988d49f67dce83e3b8782c3bf42ec78e8f87611e179a82baaaad81c401733f4c484bfdb0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
